/* Allegro data file object indexes, produced by grabber v2.2 */
/* Datafile: c:\arq\c\progs\natal\game\hapyxmas.dat */
/* Date: Mon Dec  1 13:29:18 1997 */
/* Do not hand edit! */

#define EX_GR2_01                        0        /* BMP  */
#define EX_GR2_02                        1        /* BMP  */
#define EX_GR2_03                        2        /* BMP  */
#define EX_GR3_01                        3        /* BMP  */
#define EX_GR3_02                        4        /* BMP  */
#define EX_GR3_03                        5        /* BMP  */
#define EX_GR_01                         6        /* BMP  */
#define EX_GR_02                         7        /* BMP  */
#define EX_GR_03                         8        /* BMP  */
#define EX_GR_04                         9        /* BMP  */
#define EX_GR_05                         10       /* BMP  */
#define EX_GRY2_01                       11       /* BMP  */
#define EX_GRY2_02                       12       /* BMP  */
#define EX_GRY2_03                       13       /* BMP  */
#define EX_GRY2_04                       14       /* BMP  */
#define EX_GRY2_05                       15       /* BMP  */
#define EX_GRY_01                        16       /* BMP  */
#define EX_GRY_02                        17       /* BMP  */
#define EX_GRY_03                        18       /* BMP  */
#define EX_GRY_04                        19       /* BMP  */
#define EX_GRY_05                        20       /* BMP  */
#define EX_RED2_01                       21       /* BMP  */
#define EX_RED2_02                       22       /* BMP  */
#define EX_RED2_03                       23       /* BMP  */
#define EX_RED2_04                       24       /* BMP  */
#define EX_RED_01                        25       /* BMP  */
#define EX_RED_02                        26       /* BMP  */
#define EX_RED_03                        27       /* BMP  */
#define EX_RED_04                        28       /* BMP  */
#define EX_RED_05                        29       /* BMP  */
#define EX_RED_06                        30       /* BMP  */
#define EX_SMOKE_01                      31       /* BMP  */
#define EX_SMOKE_02                      32       /* BMP  */
#define EX_WH2_01                        33       /* BMP  */
#define EX_WH2_02                        34       /* BMP  */
#define EX_WH2_03                        35       /* BMP  */
#define EX_WH_01                         36       /* BMP  */
#define EX_WH_02                         37       /* BMP  */
#define EX_WH_03                         38       /* BMP  */
#define FONT1                            39       /* FONT */
#define FONT2                            40       /* FONT */
#define midi01                           41       /* MIDI */
#define midi02                           42       /* MIDI */
#define midi03                           43       /* MIDI */
#define midi04                           44       /* MIDI */
#define midi05                           45       /* MIDI */
#define midi06                           46       /* MIDI */
#define midi07                           47       /* MIDI */
#define midi08                           48       /* MIDI */
#define midi09                           49       /* MIDI */
#define midi10                           50       /* MIDI */
#define midi11                           51       /* MIDI */
#define midi12                           52       /* MIDI */
#define midi13                           53       /* MIDI */
#define midi14                           54       /* MIDI */
#define midi15                           55       /* MIDI */
#define midi16                           56       /* MIDI */
#define midi17                           57       /* MIDI */
#define midi18                           58       /* MIDI */
#define midi19                           59       /* MIDI */
#define midi20                           60       /* MIDI */
#define midi21                           61       /* MIDI */
#define midi22                           62       /* MIDI */
#define midi23                           63       /* MIDI */
#define midi24                           64       /* MIDI */
#define midi25                           65       /* MIDI */
#define midi26                           66       /* MIDI */
#define midi27                           67       /* MIDI */
#define midi28                           68       /* MIDI */
#define midi29                           69       /* MIDI */
#define midi30                           70       /* MIDI */
#define midi31                           71       /* MIDI */
#define midi32                           72       /* MIDI */
#define midi33                           73       /* MIDI */
#define midi34                           74       /* MIDI */
#define NASTY000                         75       /* BMP  */
#define NASTY001                         76       /* BMP  */
#define NASTY002                         77       /* BMP  */
#define NASTY003                         78       /* BMP  */
#define NASTY004                         79       /* BMP  */
#define NASTY005                         80       /* BMP  */
#define NASTY006                         81       /* BMP  */
#define NASTY007                         82       /* BMP  */
#define NASTY008                         83       /* BMP  */
#define NASTY010                         84       /* BMP  */
#define NASTY011                         85       /* BMP  */
#define NASTY012                         86       /* BMP  */
#define NASTY013                         87       /* BMP  */
#define NASTY014                         88       /* BMP  */
#define NASTY015                         89       /* BMP  */
#define NASTY016                         90       /* BMP  */
#define NASTY017                         91       /* BMP  */
#define NASTY018                         92       /* BMP  */
#define NASTY019                         93       /* BMP  */
#define NASTY020                         94       /* BMP  */
#define NASTY021                         95       /* BMP  */
#define NASTY022                         96       /* BMP  */
#define NASTY023                         97       /* BMP  */
#define NAZTY000                         98       /* BMP  */
#define NAZTY001                         99       /* BMP  */
#define NAZTY002                         100      /* BMP  */
#define NAZTY003                         101      /* BMP  */
#define NAZTY004                         102      /* BMP  */
#define NAZTY005                         103      /* BMP  */
#define NAZTY006                         104      /* BMP  */
#define NAZTY007                         105      /* BMP  */
#define NAZTY008                         106      /* BMP  */
#define NAZTY009                         107      /* BMP  */
#define NAZTY010                         108      /* BMP  */
#define NAZTY011                         109      /* BMP  */
#define NAZTY012                         110      /* BMP  */
#define NAZTY013                         111      /* BMP  */
#define NAZTY014                         112      /* BMP  */
#define NAZTY015                         113      /* BMP  */
#define NAZTY016                         114      /* BMP  */
#define NAZTY017                         115      /* BMP  */
#define NAZTY018                         116      /* BMP  */
#define NAZTY019                         117      /* BMP  */
#define NAZTY020                         118      /* BMP  */
#define NAZTY021                         119      /* BMP  */
#define NAZTY022                         120      /* BMP  */
#define NAZTY023                         121      /* BMP  */
#define NAZTY024                         122      /* BMP  */
#define NAZTY025                         123      /* BMP  */
#define NAZTY026                         124      /* BMP  */
#define NAZTY028                         125      /* BMP  */
#define NAZTY029                         126      /* BMP  */
#define NAZTY030                         127      /* BMP  */
#define NAZTY031                         128      /* BMP  */
#define NAZTY032                         129      /* BMP  */
#define NAZTY033                         130      /* BMP  */
#define NAZTY034                         131      /* BMP  */
#define NAZTY035                         132      /* BMP  */
#define NAZTY036                         133      /* BMP  */
#define NAZTY037                         134      /* BMP  */
#define NAZTY038                         135      /* BMP  */
#define NAZTY039                         136      /* BMP  */
#define NAZTY040                         137      /* BMP  */
#define NAZZTY000                        138      /* BMP  */
#define NAZZTY001                        139      /* BMP  */
#define NAZZTY002                        140      /* BMP  */
#define NAZZTY003                        141      /* BMP  */
#define NAZZTY004                        142      /* BMP  */
#define NAZZTY005                        143      /* BMP  */
#define NAZZTY006                        144      /* BMP  */
#define NAZZTY007                        145      /* BMP  */
#define NAZZTY008                        146      /* BMP  */
#define NAZZTY009                        147      /* BMP  */
#define NAZZTY010                        148      /* BMP  */
#define NAZZTY011                        149      /* BMP  */
#define NAZZTY012                        150      /* BMP  */
#define NAZZTY013                        151      /* BMP  */
#define NAZZTY014                        152      /* BMP  */
#define NAZZTY015                        153      /* BMP  */
#define PALETTE_01                       154      /* PAL  */
#define POWER1                           155      /* BMP  */
#define POWER2                           156      /* BMP  */
#define POWER3                           157      /* BMP  */
#define POWER4                           158      /* BMP  */
#define POWER5                           159      /* BMP  */
#define POWER6                           160      /* BMP  */
#define PWR000                           161      /* BMP  */
#define PWR001                           162      /* BMP  */
#define PWR002                           163      /* BMP  */
#define PWR003                           164      /* BMP  */
#define PWR004                           165      /* BMP  */
#define PWR005                           166      /* BMP  */
#define PWR006                           167      /* BMP  */
#define PWR007                           168      /* BMP  */
#define PWR008                           169      /* BMP  */
#define PWR009                           170      /* BMP  */
#define PWR010                           171      /* BMP  */
#define PWR011                           172      /* BMP  */
#define PWR012                           173      /* BMP  */
#define PWR013                           174      /* BMP  */
#define PWR014                           175      /* BMP  */
#define PWR015                           176      /* BMP  */
#define PWR016                           177      /* BMP  */
#define PWR017                           178      /* BMP  */
#define PWR018                           179      /* BMP  */
#define PWR019                           180      /* BMP  */
#define PWR020                           181      /* BMP  */
#define PWR021                           182      /* BMP  */
#define PWR022                           183      /* BMP  */
#define PWR023                           184      /* BMP  */
#define PWR024                           185      /* BMP  */
#define PWR025                           186      /* BMP  */
#define PWR026                           187      /* BMP  */
#define PWR027                           188      /* BMP  */
#define PWR028                           189      /* BMP  */
#define PWR029                           190      /* BMP  */
#define SANTA1                           191      /* BMP  */
#define SANTA2                           192      /* BMP  */
#define SANTA3                           193      /* BMP  */
#define TILE000                          194      /* BMP  */
#define TILE001                          195      /* BMP  */
#define TILE002                          196      /* BMP  */
#define TILE003                          197      /* BMP  */
#define TILE004                          198      /* BMP  */
#define TILE005                          199      /* BMP  */
#define TILE006                          200      /* BMP  */
#define TILE007                          201      /* BMP  */
#define TILE008                          202      /* BMP  */
#define TILE009                          203      /* BMP  */
#define TILE010                          204      /* BMP  */
#define TILE011                          205      /* BMP  */
#define TILE012                          206      /* BMP  */
#define TILE013                          207      /* BMP  */
#define TILE014                          208      /* BMP  */
#define TILE015                          209      /* BMP  */
#define TILE016                          210      /* BMP  */
#define TILE017                          211      /* BMP  */
#define TILE018                          212      /* BMP  */
#define TILE019                          213      /* BMP  */
#define TILE020                          214      /* BMP  */
#define TILE021                          215      /* BMP  */
#define TILE022                          216      /* BMP  */
#define TILE023                          217      /* BMP  */
#define TILE024                          218      /* BMP  */
#define TILE025                          219      /* BMP  */
#define TILE026                          220      /* BMP  */
#define TILE027                          221      /* BMP  */
#define TILE028                          222      /* BMP  */
#define TILE029                          223      /* BMP  */
#define TILE030                          224      /* BMP  */
#define TILE031                          225      /* BMP  */
#define TILE032                          226      /* BMP  */
#define TILE033                          227      /* BMP  */
#define TILE034                          228      /* BMP  */
#define TILE035                          229      /* BMP  */
#define TILE036                          230      /* BMP  */
#define TILE037                          231      /* BMP  */
#define TILE038                          232      /* BMP  */
#define TILE039                          233      /* BMP  */
#define TILE040                          234      /* BMP  */
#define TILE041                          235      /* BMP  */
#define TILE042                          236      /* BMP  */
#define TILE043                          237      /* BMP  */
#define TILE044                          238      /* BMP  */
#define TILE045                          239      /* BMP  */
#define TILE046                          240      /* BMP  */
#define TILE047                          241      /* BMP  */
#define TILE048                          242      /* BMP  */
#define TILE049                          243      /* BMP  */
#define TILE050                          244      /* BMP  */
#define TILE051                          245      /* BMP  */
#define TILE052                          246      /* BMP  */
#define TILE053                          247      /* BMP  */
#define TILE054                          248      /* BMP  */
#define TILE055                          249      /* BMP  */
#define TILE056                          250      /* BMP  */
#define TILE057                          251      /* BMP  */
#define TILE058                          252      /* BMP  */
#define TILE059                          253      /* BMP  */
#define TILE060                          254      /* BMP  */
#define TILE061                          255      /* BMP  */
#define TILE062                          256      /* BMP  */
#define TILE063                          257      /* BMP  */
#define TILE064                          258      /* BMP  */
#define TILE065                          259      /* BMP  */
#define TILE066                          260      /* BMP  */
#define TILE067                          261      /* BMP  */
#define TILE068                          262      /* BMP  */
#define TILE069                          263      /* BMP  */
#define TILE070                          264      /* BMP  */
#define TILE071                          265      /* BMP  */
#define TILE072                          266      /* BMP  */
#define TILE073                          267      /* BMP  */
#define TILE074                          268      /* BMP  */
#define TILE075                          269      /* BMP  */
#define TILE076                          270      /* BMP  */
#define TILE077                          271      /* BMP  */
#define TILE078                          272      /* BMP  */
#define TILE079                          273      /* BMP  */
#define TILE080                          274      /* BMP  */
#define TILE081                          275      /* BMP  */
#define TILE082                          276      /* BMP  */
#define TILE083                          277      /* BMP  */
#define TILE084                          278      /* BMP  */
#define TILE085                          279      /* BMP  */
#define TILE086                          280      /* BMP  */
#define TILE087                          281      /* BMP  */
#define TILE088                          282      /* BMP  */
#define TILE089                          283      /* BMP  */
#define TILE090                          284      /* BMP  */
#define TILE091                          285      /* BMP  */
#define TILE092                          286      /* BMP  */
#define TILE093                          287      /* BMP  */
#define TILE094                          288      /* BMP  */
#define TILE095                          289      /* BMP  */
#define TILE096                          290      /* BMP  */
#define TILE097                          291      /* BMP  */
#define TILE098                          292      /* BMP  */
#define TILE099                          293      /* BMP  */
#define TILE100                          294      /* BMP  */
#define TILE101                          295      /* BMP  */
#define TILE102                          296      /* BMP  */
#define TILE103                          297      /* BMP  */
#define TILE104                          298      /* BMP  */
#define TILE105                          299      /* BMP  */
#define TILE106                          300      /* BMP  */
#define TILE107                          301      /* BMP  */
#define TILE108                          302      /* BMP  */
#define TILE109                          303      /* BMP  */
#define TILE110                          304      /* BMP  */
#define TILE111                          305      /* BMP  */
#define TILE112                          306      /* BMP  */
#define TILE113                          307      /* BMP  */
#define TILE114                          308      /* BMP  */
#define TILE115                          309      /* BMP  */
#define TILE116                          310      /* BMP  */
#define TILE117                          311      /* BMP  */
#define TILE118                          312      /* BMP  */
#define TILE119                          313      /* BMP  */
#define TILE120                          314      /* BMP  */
#define TILE121                          315      /* BMP  */
#define TILE122                          316      /* BMP  */
#define TILE123                          317      /* BMP  */
#define TILE124                          318      /* BMP  */
#define TILE125                          319      /* BMP  */
#define TILE126                          320      /* BMP  */
#define TILE127                          321      /* BMP  */
#define TILE128                          322      /* BMP  */
#define TILE129                          323      /* BMP  */
#define TILE130                          324      /* BMP  */
#define TILE131                          325      /* BMP  */
#define TILE132                          326      /* BMP  */
#define TILE133                          327      /* BMP  */
#define TILE134                          328      /* BMP  */
#define TILE135                          329      /* BMP  */
#define TILE136                          330      /* BMP  */
#define TILE137                          331      /* BMP  */
#define TILE138                          332      /* BMP  */
#define TILE139                          333      /* BMP  */
#define TILE140                          334      /* BMP  */
#define TILE141                          335      /* BMP  */
#define TILE142                          336      /* BMP  */
#define TILE143                          337      /* BMP  */
#define TILE144                          338      /* BMP  */
#define TILE145                          339      /* BMP  */
#define TILE146                          340      /* BMP  */
#define TILE147                          341      /* BMP  */
#define TILE148                          342      /* BMP  */
#define TILE149                          343      /* BMP  */
#define TILE150                          344      /* BMP  */
#define TILE151                          345      /* BMP  */
#define TILE152                          346      /* BMP  */
#define TILE153                          347      /* BMP  */
#define TILE154                          348      /* BMP  */
#define TILE155                          349      /* BMP  */
#define TILE156                          350      /* BMP  */
#define TILE157                          351      /* BMP  */
#define TILE158                          352      /* BMP  */
#define TILE159                          353      /* BMP  */
#define TILE160                          354      /* BMP  */
#define TILE161                          355      /* BMP  */
#define TILE162                          356      /* BMP  */
#define TILE163                          357      /* BMP  */
#define TILE164                          358      /* BMP  */
#define TILE165                          359      /* BMP  */
#define TILE166                          360      /* BMP  */
#define TILE167                          361      /* BMP  */
#define TILE168                          362      /* BMP  */
#define TILE169                          363      /* BMP  */
#define TILE170                          364      /* BMP  */
#define TILE171                          365      /* BMP  */
#define TILE172                          366      /* BMP  */
#define TILE173                          367      /* BMP  */
#define TILE174                          368      /* BMP  */
#define TILE175                          369      /* BMP  */
#define TILE176                          370      /* BMP  */
#define TILE177                          371      /* BMP  */
#define TILE178                          372      /* BMP  */
#define TILE179                          373      /* BMP  */
#define TILE180                          374      /* BMP  */
#define TILE181                          375      /* BMP  */
#define TILE182                          376      /* BMP  */
#define TILE183                          377      /* BMP  */
#define TILE184                          378      /* BMP  */
#define TILE185                          379      /* BMP  */
#define TILE186                          380      /* BMP  */
#define TILE187                          381      /* BMP  */
#define TILE188                          382      /* BMP  */
#define TILE189                          383      /* BMP  */
#define TILE190                          384      /* BMP  */
#define TILE191                          385      /* BMP  */
#define TILE192                          386      /* BMP  */
#define TILE193                          387      /* BMP  */
#define TILE194                          388      /* BMP  */
#define TILE195                          389      /* BMP  */
#define TILE196                          390      /* BMP  */
#define TILE197                          391      /* BMP  */
#define TILE198                          392      /* BMP  */
#define TILE199                          393      /* BMP  */
#define TILE200                          394      /* BMP  */
#define TILE201                          395      /* BMP  */
#define TILE202                          396      /* BMP  */
#define TILE203                          397      /* BMP  */
#define TILE204                          398      /* BMP  */
#define TILE205                          399      /* BMP  */
#define TILE206                          400      /* BMP  */
#define TILE207                          401      /* BMP  */
#define TILE208                          402      /* BMP  */
#define TILE209                          403      /* BMP  */
#define TILE210                          404      /* BMP  */
#define TILE211                          405      /* BMP  */
#define TILE212                          406      /* BMP  */
#define TILE213                          407      /* BMP  */
#define TILE214                          408      /* BMP  */
#define TILE215                          409      /* BMP  */
#define TILE216                          410      /* BMP  */
#define TILE217                          411      /* BMP  */
#define TILE218                          412      /* BMP  */
#define TILE219                          413      /* BMP  */
#define TILE220                          414      /* BMP  */
#define TILE221                          415      /* BMP  */
#define TILE222                          416      /* BMP  */
#define TILE223                          417      /* BMP  */
#define TILE224                          418      /* BMP  */
#define TILE225                          419      /* BMP  */
#define TILE226                          420      /* BMP  */
#define TILE227                          421      /* BMP  */
#define TILE228                          422      /* BMP  */
#define TILE229                          423      /* BMP  */
#define TILE230                          424      /* BMP  */
#define TILE231                          425      /* BMP  */
#define TILE232                          426      /* BMP  */
#define TILE233                          427      /* BMP  */
#define TILE234                          428      /* BMP  */
#define TILE235                          429      /* BMP  */
#define TILE236                          430      /* BMP  */
#define TILE237                          431      /* BMP  */
#define TILE238                          432      /* BMP  */
#define TILE239                          433      /* BMP  */
#define TILE240                          434      /* BMP  */
#define TILE241                          435      /* BMP  */
#define TILE242                          436      /* BMP  */
#define TILE243                          437      /* BMP  */
#define TILE244                          438      /* BMP  */
#define TILE245                          439      /* BMP  */
#define TILE246                          440      /* BMP  */
#define TILE247                          441      /* BMP  */
#define TILE248                          442      /* BMP  */
#define TILE249                          443      /* BMP  */
#define TILE250                          444      /* BMP  */
#define TILE251                          445      /* BMP  */
#define TILE252                          446      /* BMP  */
#define TILE253                          447      /* BMP  */
#define TILE254                          448      /* BMP  */
#define TILE255                          449      /* BMP  */
#define TILE256                          450      /* BMP  */
#define TILE257                          451      /* BMP  */
#define TILE258                          452      /* BMP  */
#define TILE259                          453      /* BMP  */
#define TILE260                          454      /* BMP  */
#define TILE261                          455      /* BMP  */
#define TILE262                          456      /* BMP  */
#define TILE263                          457      /* BMP  */
#define TILE264                          458      /* BMP  */
#define TILE265                          459      /* BMP  */
#define TILE266                          460      /* BMP  */
#define TILE267                          461      /* BMP  */
#define TILE268                          462      /* BMP  */
#define TILE269                          463      /* BMP  */
#define TILE270                          464      /* BMP  */
#define TILE271                          465      /* BMP  */
#define TILE272                          466      /* BMP  */
#define TILE273                          467      /* BMP  */
#define TILE274                          468      /* BMP  */
#define TILE275                          469      /* BMP  */
#define TILE276                          470      /* BMP  */
#define TILE277                          471      /* BMP  */
#define TILE278                          472      /* BMP  */
#define TILE279                          473      /* BMP  */
#define TILE280                          474      /* BMP  */
#define TILE281                          475      /* BMP  */
#define TILE282                          476      /* BMP  */
#define TILE283                          477      /* BMP  */
#define TILE284                          478      /* BMP  */
#define TILE285                          479      /* BMP  */
#define TILE286                          480      /* BMP  */
#define TILE287                          481      /* BMP  */
#define TILE288                          482      /* BMP  */
#define TILE289                          483      /* BMP  */
#define TILE290                          484      /* BMP  */
#define TILE291                          485      /* BMP  */
#define TILE292                          486      /* BMP  */
#define TILE293                          487      /* BMP  */
#define TILE294                          488      /* BMP  */
#define TILE295                          489      /* BMP  */
#define TILE296                          490      /* BMP  */
#define TILE297                          491      /* BMP  */
#define TILE298                          492      /* BMP  */
#define TILE299                          493      /* BMP  */
#define TILE300                          494      /* BMP  */
#define TILE301                          495      /* BMP  */
#define TILE302                          496      /* BMP  */
#define TILE303                          497      /* BMP  */
#define TILE304                          498      /* BMP  */
#define TILE305                          499      /* BMP  */
#define TILE306                          500      /* BMP  */
#define TILE307                          501      /* BMP  */
#define TILE308                          502      /* BMP  */
#define TILE309                          503      /* BMP  */
#define TILE310                          504      /* BMP  */
#define TILE311                          505      /* BMP  */
#define TILE312                          506      /* BMP  */
#define TILE313                          507      /* BMP  */
#define TILE314                          508      /* BMP  */
#define TILE315                          509      /* BMP  */
#define TILE316                          510      /* BMP  */
#define TILE317                          511      /* BMP  */
#define TILE318                          512      /* BMP  */
#define TILE319                          513      /* BMP  */
#define TILE320                          514      /* BMP  */
#define TILE321                          515      /* BMP  */
#define TILE322                          516      /* BMP  */
#define TILE323                          517      /* BMP  */
#define TILE324                          518      /* BMP  */
#define TILE325                          519      /* BMP  */
#define TILE326                          520      /* BMP  */
#define TILE327                          521      /* BMP  */
#define TILE328                          522      /* BMP  */
#define TILE329                          523      /* BMP  */
#define TILE330                          524      /* BMP  */
#define TILE331                          525      /* BMP  */
#define TILE332                          526      /* BMP  */
#define TILE333                          527      /* BMP  */
#define TILE334                          528      /* BMP  */
#define TILE335                          529      /* BMP  */

